#!/bin/bash
# Start REFINE production stack (web + Java backend + LangGraph agents).
# Ports and feature flags: REFINE/config/ports.env
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "$0")/.." && pwd)"
PID_DIR="$SCRIPT_DIR/.run"
mkdir -p "$PID_DIR"

PORTS_FILE="$SCRIPT_DIR/config/ports.env"
if [ ! -f "$PORTS_FILE" ] && [ -f "$SCRIPT_DIR/config/ports.env.example" ]; then
  cp "$SCRIPT_DIR/config/ports.env.example" "$PORTS_FILE"
  echo "Created $PORTS_FILE from ports.env.example"
fi
if [ -f "$PORTS_FILE" ]; then
  # shellcheck disable=SC1091
  source "$PORTS_FILE"
elif [ -f "$SCRIPT_DIR/config/ports.env.example" ]; then
  echo "WARN: using ports.env.example — copy to config/ports.env for local overrides"
  # shellcheck disable=SC1091
  source "$SCRIPT_DIR/config/ports.env.example"
fi

FRONTEND_PORT="${FRONTEND_PORT:-3001}"
BACKEND_PORT="${BACKEND_PORT:-8084}"
AGENTS_PORT="${AGENTS_PORT:-8092}"
ENABLE_BASELINE_COMPARISON="${ENABLE_BASELINE_COMPARISON:-0}"
ENABLE_RESEARCH_EXPORT_UI="${ENABLE_RESEARCH_EXPORT_UI:-0}"
NEXT_PUBLIC_REFINE_DEMO="${NEXT_PUBLIC_REFINE_DEMO:-1}"
NEXT_PUBLIC_BRAND_NAME="${NEXT_PUBLIC_BRAND_NAME:-REFINE}"

sync_frontend_env() {
  cat > "$SCRIPT_DIR/web/app/.env.local" <<EOF
# Auto-generated by start-refine.sh
NEXT_PUBLIC_FRONTEND_PORT=${FRONTEND_PORT}
NEXT_PUBLIC_API_PORT=${BACKEND_PORT}
NEXT_PUBLIC_AGENTS_PORT=${AGENTS_PORT}
NEXT_PUBLIC_ENABLE_BASELINE_COMPARISON=${ENABLE_BASELINE_COMPARISON}
NEXT_PUBLIC_ENABLE_RESEARCH_EXPORT_UI=${ENABLE_RESEARCH_EXPORT_UI}
NEXT_PUBLIC_REFINE_DEMO=${NEXT_PUBLIC_REFINE_DEMO}
NEXT_PUBLIC_BRAND_NAME=${NEXT_PUBLIC_BRAND_NAME}
EOF
}

stop_all() {
  echo "Stopping REFINE services..."
  for f in "$PID_DIR"/*.pid; do
    [ -f "$f" ] || continue
    pid=$(cat "$f")
    kill "$pid" 2>/dev/null || true
    rm -f "$f"
  done
  for port in "$FRONTEND_PORT" "$BACKEND_PORT" "$AGENTS_PORT"; do
    lsof -t -iTCP:"$port" -sTCP:LISTEN 2>/dev/null | xargs kill 2>/dev/null || true
  done
  pkill -f "uvicorn main:app" 2>/dev/null || true
  pkill -f "next dev -p ${FRONTEND_PORT}" 2>/dev/null || true
  pkill -f "refactai-server-0.1.0-SNAPSHOT.jar" 2>/dev/null || true
  sleep 1
}

run_detached() {
  local logfile="$1"
  shift
  local detach="$SCRIPT_DIR/scripts/detach_daemon.py"
  if [ ! -f "$detach" ]; then
    nohup "$@" </dev/null >>"$logfile" 2>&1 &
    disown -h 2>/dev/null || disown 2>/dev/null || true
    return 0
  fi
  python3 "$detach" "$logfile" -- "$@" >/dev/null 2>&1 || {
    nohup "$@" </dev/null >>"$logfile" 2>&1 &
    disown -h 2>/dev/null || disown 2>/dev/null || true
  }
}

wait_for_listen_pid() {
  local port="$1"
  local pid=""
  for _ in $(seq 1 45); do
    pid=$(lsof -t -iTCP:"$port" -sTCP:LISTEN 2>/dev/null | head -1)
    if [ -n "$pid" ]; then
      echo "$pid"
      return 0
    fi
    sleep 1
  done
  return 1
}

start_backend() {
  local jar="$SCRIPT_DIR/backend/server/target/refactai-server-0.1.0-SNAPSHOT.jar"
  if [ ! -f "$jar" ]; then
    echo "Building backend JAR..."
    (cd "$SCRIPT_DIR/backend/server" && mvn -q -DskipTests package)
  fi
  run_detached "$SCRIPT_DIR/backend/server.log" java -Xms512m -Xmx2g -jar "$jar" --server.port="$BACKEND_PORT"
  local pid
  pid=$(wait_for_listen_pid "$BACKEND_PORT") || { echo "ERROR: backend did not start on port $BACKEND_PORT"; return 1; }
  echo "$pid" > "$PID_DIR/backend.pid"
  echo "Backend PID $pid → http://127.0.0.1:${BACKEND_PORT}/api"
}

start_agents() {
  cd "$SCRIPT_DIR/agents"
  if [ -f ".env" ]; then
    set -a
    # shellcheck disable=SC1091
    source .env
    set +a
  fi
  export BACKEND_BASE="http://127.0.0.1:${BACKEND_PORT}/api"
  export PORT="$AGENTS_PORT"
  export ENABLE_BASELINE_COMPARISON="${ENABLE_BASELINE_COMPARISON}"
  export PYENV_VERSION=3.10.13
  if ! python3 -c "import uvicorn" 2>/dev/null; then
    echo "ERROR: Python 3.10.13 needs uvicorn. Run: PYENV_VERSION=3.10.13 pip install -r $SCRIPT_DIR/agents/requirements.txt"
    exit 1
  fi
  run_detached "$SCRIPT_DIR/agents/agents.log" \
    env -u OPENAI_API_KEY -u GOOGLE_API_KEY -u ANTHROPIC_API_KEY \
    BACKEND_BASE="http://127.0.0.1:${BACKEND_PORT}/api" \
    PORT="$PORT" \
    ENABLE_BASELINE_COMPARISON="${ENABLE_BASELINE_COMPARISON}" \
    PYENV_VERSION=3.10.13 \
    python3 -m uvicorn main:app --host 0.0.0.0 --port "$PORT"
  local pid
  pid=$(wait_for_listen_pid "$PORT") || { echo "ERROR: agents did not start on port $PORT"; return 1; }
  echo "$pid" > "$PID_DIR/agents.pid"
  echo "Agents PID $pid → http://127.0.0.1:${AGENTS_PORT}/agents (LangGraph orchestration)"
}

start_frontend() {
  sync_frontend_env
  cd "$SCRIPT_DIR/web/app"
  if [ ! -d node_modules ]; then
    echo "Installing frontend dependencies..."
    npm ci
  fi
  run_detached "$SCRIPT_DIR/frontend.log" npx next dev -p "$FRONTEND_PORT" -H 0.0.0.0
  local pid
  pid=$(wait_for_listen_pid "$FRONTEND_PORT") || { echo "ERROR: frontend did not start on port $FRONTEND_PORT"; return 1; }
  echo "$pid" > "$PID_DIR/frontend.pid"
  echo "Frontend PID $pid → http://127.0.0.1:${FRONTEND_PORT}"
}

port_listener_pid() {
  lsof -t -iTCP:"$1" -sTCP:LISTEN 2>/dev/null | head -1 || true
}

status_all() {
  echo "REFINE ports: frontend=${FRONTEND_PORT} backend=${BACKEND_PORT} agents=${AGENTS_PORT}"
  echo "Flags: baseline=${ENABLE_BASELINE_COMPARISON} research_hub=${ENABLE_RESEARCH_EXPORT_UI}"
  echo ""
  for name in backend agents frontend; do
    pf="$PID_DIR/$name.pid"
    case "$name" in
      backend) port="$BACKEND_PORT" ;;
      agents) port="$AGENTS_PORT" ;;
      frontend) port="$FRONTEND_PORT" ;;
    esac
    live_pid=""
    if [ -f "$pf" ] && kill -0 "$(cat "$pf")" 2>/dev/null; then
      live_pid=$(cat "$pf")
    fi
    if [ -z "$live_pid" ]; then
      live_pid=$(port_listener_pid "$port")
    fi
    if [ -n "$live_pid" ] && [ -f "$pf" ] && [ "$(cat "$pf")" != "$live_pid" ]; then
      echo "$live_pid" > "$pf"
    fi
    if [ -n "$live_pid" ]; then
      echo "  ✅ $name running (PID $live_pid, port $port)"
    else
      echo "  ❌ $name not running (port $port)"
    fi
  done
  echo ""
  curl -s -o /dev/null -w "  HTTP ${FRONTEND_PORT}: %{http_code}\n" --connect-timeout 3 "http://127.0.0.1:${FRONTEND_PORT}" 2>/dev/null || echo "  HTTP ${FRONTEND_PORT}: down"
  curl -s -o /dev/null -w "  HTTP ${BACKEND_PORT}: %{http_code}\n" --connect-timeout 3 "http://127.0.0.1:${BACKEND_PORT}/api/health" 2>/dev/null || echo "  HTTP ${BACKEND_PORT}: down"
  curl -s -o /dev/null -w "  HTTP ${AGENTS_PORT}: %{http_code}\n" --connect-timeout 3 "http://127.0.0.1:${AGENTS_PORT}/agents/health" 2>/dev/null || echo "  HTTP ${AGENTS_PORT}: down"
  echo ""
  echo "  Open REFINE: http://127.0.0.1:${FRONTEND_PORT}"
}

case "${1:-start}" in
  stop) stop_all ;;
  status) status_all ;;
  restart) stop_all; sync_frontend_env; start_backend; start_agents; start_frontend; sleep 15; status_all ;;
  start-if-up)
    sync_frontend_env
    if [ -n "$(port_listener_pid "$FRONTEND_PORT")" ] && [ -n "$(port_listener_pid "$BACKEND_PORT")" ] && [ -n "$(port_listener_pid "$AGENTS_PORT")" ]; then
      echo "All REFINE services already running."
      status_all
      exit 0
    fi
    start_backend
    start_agents
    start_frontend
    sleep 15
    status_all
    ;;
  *)
    stop_all
    sync_frontend_env
    start_backend
    start_agents
    start_frontend
    echo ""
    echo "Waiting for REFINE services (15s)..."
    sleep 15
    status_all
    ;;
esac
